### ISSUE TITLE
Keystore crashes in Android P emulator

### ISSUE THREAD

**Issue by nildeka** [googlesamples/android-BasicAndroidKeyStore#2]
I am using Android P x86 emulator. But the generating keystore crashes the application. Below are the crash logs:

```
Process: com.example.android.basicandroidkeystore, PID: 5712
java.security.ProviderException: Failed to load generated key pair from keystore
   at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:530)
   at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:478)
  at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
   at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.createKeys(BasicAndroidKeyStoreFragment.java:211)
   at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:89)
   at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394)at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326)
   at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386)
   at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1236)
   at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:775)
   at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:922)
   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:912)
   at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:617)
   at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147)
   at android.view.View.performClick(View.java:6579)
   at android.view.View.performClickInternal(View.java:6556)
   at android.view.View.access$3100(View.java:777)
   at android.view.View$PerformClick.run(View.java:25660)
   at android.os.Handler.handleCallback(Handler.java:819)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6656)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:239)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:278)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:289)
   at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKey 
   at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:478) 
at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
   at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.createKeys(BasicAndroidKeyStoreFragment.java:211) 
    at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:89) 
  at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394) 
    at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326) 
    at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344) 
   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386) 
   at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1236) 
   at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:775) 
   at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167) 
   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:922) 
   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:912) 
   at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:617) 
   at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147) 
   at android.view.View.performClick(View.java:6579) 
   at android.view.View.performClickInternal(View.java:6556) 
   at android.view.View.access$3100(View.java:777) 
   at android.view.View$PerformClick.run(View.java:25660) 
   at android.os.Handler.handleCallback(Handler.java:819) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:164) 
   at android.app.ActivityThread.main(ActivityThread.java:6656) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
Caused by: android.security.KeyStoreException: Invalid key blob
   at android.security.KeyStore.getKeyStoreException(KeyStore.java:823)
   at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:241)
   at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:278) 
   at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:289) 
   at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:521) 
   at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:478) 
   at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
   at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.createKeys(BasicAndroidKeyStoreFragment.java:211) 
   at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:89) 
   at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394) 
   at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326) 
   at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344) 
   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386) 
   at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1236) 
   at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:775) 
   at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167) 
   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:922) 
   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:912) 
   at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:617) 
   at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147) 
   at android.view.View.performClick(View.java:6579) 
   at android.view.View.performClickInternal(View.java:6556) 
   at android.view.View.access$3100(View.java:777) 
   at android.view.View$PerformClick.run(View.java:25660) 
   at android.os.Handler.handleCallback(Handler.java:819) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:164) 
   at android.app.ActivityThread.main(ActivityThread.java:6656) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 

```
       
Could you please help me solve this, because in my application also I am using keystore and because of the crash, I cannot use the application.

Thanks,
Nilanjana

**Comment by laszlo-major** [comment]
It's a reported bug https://issuetracker.google.com/issues/74355119  but the silence on it is frankly terrifying, considering how it completely breaks any encryption leveraging the keystore...

**Comment by iskugor** [comment]
I have same crash on Samsung A3 (2016) device with Android 6.0.1.

Works fine on Android P though.


Anyone found workaround?

**Comment by iskugor** [comment]
Actually, I just noticed my stacktrace it a bit different:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.basicandroidkeystore, PID: 2694
    java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:491)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.createKeys(BasicAndroidKeyStoreFragment.java:211)
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:89)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386)
        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1249)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)
        at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:726)
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:239)
        at android.view.View.performClick(View.java:5714)
        at android.widget.TextView.performClick(TextView.java:10926)
        at android.view.View$PerformClick.run(View.java:22589)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:252)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:488)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.createKeys(BasicAndroidKeyStoreFragment.java:211) 
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:89) 
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394) 
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326) 
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344) 
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386) 
        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1249) 
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801) 
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158) 
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954) 
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944) 
        at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:726) 
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:239) 
        at android.view.View.performClick(View.java:5714) 
        at android.widget.TextView.performClick(TextView.java:10926) 
        at android.view.View$PerformClick.run(View.java:22589) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7325) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: android.security.KeyStoreException: OK
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:918)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223) 
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:252) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:488) 
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.createKeys(BasicAndroidKeyStoreFragment.java:211) 
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:89) 
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394) 
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326) 
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344) 
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386) 
        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1249) 
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801) 
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158) 
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954) 
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944) 
        at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:726) 
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:239) 
        at android.view.View.performClick(View.java:5714) 
        at android.widget.TextView.performClick(TextView.java:10926) 
        at android.view.View$PerformClick.run(View.java:22589) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7325) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```


In particular, I'm getting:

> Caused by: android.security.KeyStoreException: OK

while in your case it's:

> Caused by: android.security.KeyStoreException: Invalid key blob

**Comment by AdamGold** [comment]
Any news on this issue?

**Comment by filipkowicz** [comment]
?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
